services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    # aliases
    Jalismrs\Symfony\Bundle\JalismrsApiThrottlerBundle\ApiThrottler: '@jalismrs_api_throttler.api_throttler'
    
    # services
    jalismrs_api_throttler.api_throttler:
        arguments:
            $rateLimitProvider: '@jalismrs_api_throttler.dependency.maba.gentle_force.rate_limit_provider'
            $throttler: '@Maba\GentleForce\ThrottlerInterface'
            $cap: '%jalismrs_api_throttler.cap%'
            $caps: '%jalismrs_api_throttler.caps%'
        class: 'Jalismrs\Symfony\Bundle\JalismrsApiThrottlerBundle\ApiThrottler'
    
    # DEPENDENCIES -------------------------------------------------------------
    # maba/gentle-force
    jalismrs_api_throttler.dependency.maba.gentle_force.rate_limit_provider:
        class: 'Maba\GentleForce\RateLimitProvider'
    jalismrs_api_throttler.dependency.maba.gentle_force.throttler:
        arguments:
            $client: '@jalismrs_api_throttler.dependency.predis.predis.client'
            $rateLimitProvider: '@jalismrs_api_throttler.dependency.maba.gentle_force.rate_limit_provider'
            $prefix: 'rate_limit::'
        class: 'Maba\GentleForce\Throttler'
    
    Maba\GentleForce\ThrottlerInterface: '@jalismrs_api_throttler.dependency.maba.gentle_force.throttler'
    
    # predis/predis
    jalismrs_api_throttler.dependency.predis.predis.client:
        arguments:
            $parameters: '%jalismrs_api_throttler.redis.parameters%'
            $options: '%jalismrs_api_throttler.redis.options%'
        class: 'Predis\Client'
