services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    api_throttler.api_throttler:
        class: 'Jalismrs\Symfony\Bundle\ApiThrottlerBundle\ApiThrottler'
        arguments:
            $rateLimitProvider: '@Maba\GentleForce\RateLimitProvider'
            $throttler: '@Maba\GentleForce\ThrottlerInterface'
    
    Jalismrs\Symfony\Bundle\ApiThrottlerBundle\ApiThrottler: '@api_throttler.api_throttler'
    
    # maba/gentle-force
    Maba\GentleForce\RateLimitProvider:
        autowire: true
    Maba\GentleForce\Throttler:
        arguments:
            $client: '@Predis\Client'
            $rateLimitProvider: '@Maba\GentleForce\RateLimitProvider'
            $prefix: 'rate_limit::'
    Maba\GentleForce\ThrottlerInterface: '@Maba\GentleForce\Throttler'
    
    # predis/predis
    Predis\Client:
        arguments:
            $parameters:
                host: '%env(REDIS_HOST)%'
            $options:
                prefix: '%app.name%::'
